### ISSUE TITLE
http://localhost:3099/

### ISSUE THREAD

**Issue by LaxmanFareportal** [braintree/popup-bridge-ios#12] opened 2018-05-22 14:13 UTC
### General information

Have completed 1-3 steps.

Please explain what this URL actually is? I am getting blank page on my app.
**(http://localhost:3099/)** What should be this URL on my App?

Also if we run the popupbridgeexample target. The simulator shows blank and nothing really happens. Could you please let me know the issue. 

Thanks,
Laxman

* SDK/Library version: 
* iOS Version and Device: 
* Integration type and version:

**Comment by crookedneighbor** [comment] 2018-05-22 15:59
Closed as a duplicate of https://github.com/braintree/popup-bridge-ios/issues/11

**Closed by crookedneighbor** 2018-05-22 15:59 UTC
